version: 0.1

phases:
  install:
    commands:
      - npm install -g yarn
      - yarn install
      - npm install --save i18next
      - npm install --save react-i18next
      - npm install @material-ui/core
      - npm install @material-ui/icons
  build:
    commands:
      - yarn run build
  post_build:
    commands:
    - aws s3 cp --recursive --acl public-read ./build s3://drygielski.com/